version: "3.8"
services:
  backend:
    build: ./backend
    ports:
      # - "4000:4000" # Express server port
      - "8080:8080" # WebSocket server port
    env_file:
      - ./backend/.env # Load environment variables from .env file
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
  redis:
    image: redis:latest
    ports:
      - "6379:6379" # Default Redis port
  frontend:
    build: ./frontend
    ports:
      - "3000:80"
